#!/usr/bin/env bash

version="cluj-0.1.0-standalone"
repo=${HOME}/.m2

clojure=$(find ${repo} -iname ${version}.jar)

if [[ "" = "$@" ]] ; then
  rlwrap java -jar ${clojure} "$@"
else
  java -jar ${clojure} "$@"
fi
