#!/usr/bin/env bash

root=$(cd $(dirname $0) > /dev/null ; pwd)
bash=`which bash`
rlwrap=`which rlwrap`

vers="6"

version="cluj-${vers}-standalone.jar"
local="${root}/${version}"
system="${HOME}/.cluj/${version}"

if [ -e "${local}" ]; then
  clujar="${local}"
else
  clujar="${system}"
fi

if [ ! -e ${clujar} ]; then
  echo "cluj not found: expected in [${local}] or [${system}]"
  exit 1
fi

if [[ "" = "$@" ]] ; then
  echo "Cluj ${vers}"
  ${rlwrap} java -jar ${clujar} "$@"
else
  java -jar ${clujar} "$@"
fi
